version: 2

project_name: stackrun

builds:
  - id: stackrun
    main: ./cmd/stackrun
    binary: stackrun
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/rithikamandiv-ux/stackrun/internal/cli.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
      - "^chore"
      - "^Merge pull request"
      - "^Merge branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Other changes
      order: 999

release:
  draft: true
  prerelease: auto